name: 'Polkadot - Cybergov Proposal Processor'

run-name: "üó≥Ô∏è Process Proposal #${{ inputs.proposal_id }} on Polkadot"

on:
  workflow_dispatch:
    inputs:
      proposal_id:
        description: 'Proposal ID to process'
        required: true
        type: string

jobs:
  cybergov:
    name: 'Cybergov for #${{ inputs.proposal_id }} on Polkadot'
    runs-on: ubuntu-latest

    env:
      PROPOSAL_ID: ${{ inputs.proposal_id }}
      NETWORK: 'polkadot'
      FIREBASE_CREDENTIALS_JSON: ${{ secrets.FIREBASE_CREDENTIALS_JSON }}
      POLKASSEMBLY_API_KEY: ${{ secrets.POLKASSEMBLY_API_KEY }}
      OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
      

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run evaluation script
        run: python src/votebot_evaluate_single_proposal_and_vote.py
